#!/bin/sh
set -e

# Do one build to make sure the build script is working
TEST_ENV="foo" hexmake test

# Check the output
cmp -s out/test.txt <<EOF
foo
EOF

# Running the build again should extract the value from cache
TEST_ENV="foo" hexmake test | grep -q Retrieved

cmp -s out/test.txt <<EOF
foo
EOF

# Check that changing the environment variable should cause a rebuild
TEST_ENV="bar" hexmake test | grep -qv Retrieved

cmp -s out/test.txt <<EOF
bar
EOF
